### ISSUE TITLE
Creating behaviour implementing paradigm

### ISSUE THREAD

**Issue by maksimil** [philip-peterson/rust-rdom#12]
Currently we have separate structs for behaviours, I think that behaviours should be implememted with traits. But some behaviours have storages, so for them we can add the BehaviourNameStorage field to the implementing struct. Because behaviour is dependent on its storage and mostly nothing else implementation would be mostly the same for every implementor, so it could be done by macros to avoid code repetition.

**Comment by philip-peterson** [comment]
I agree if we could encapsulate behaviors in traits that would be ideal. As you correctly noted, there is one main challenge with that, which is that a trait cannot specify that a field must be present on the implementing struct. That makes it difficult to keep storage. This may be possible with macros -- let's hold off on it for a bit though because I am likely going to overhaul the macros to use `proc_macro` in the next few days. If you'd like to do a proof of concept though in the meantime, totally fine by me, just wanted you to be aware of the shifting ground.

**Comment by maksimil** [comment]
A proof of concept is at [maksimil/change_behaviour_implementation](https://github.com/philip-peterson/rust-rdom/tree/maksimil/change_behaviour_implementation). I will probably create a new branch for the actual PR, because this one will get outdated.

**Comment by maksimil** [comment]
Btw, it also closes #4 with SandboxMemberBehaviour.
