### ISSUE TITLE
Node polymorphism using enums

### ISSUE THREAD

**Issue by maksimil** [philip-peterson/rust-rdom#24]
We can see in [mdn docs](https://developer.mozilla.org/en-US/docs/Web/API/Node/nodeType) that there are only 11 types of nodes. I think that with that little types we can use an `enum` instead of a `trait`. This will also solve a problem of intertrait casting, since we really only needed it between `Arc<dyn AnyNode>` and `Arc<dyn AnyElement>`.

**Comment by philip-peterson** [comment]
Thanks for the suggestion, it's an interesting idea. The main issue I see with this is that it ceases to be possible to refer to a node of a specific type (e.g. `AttrNode` while having that be statically correct). It may be something we can build out a prototype for though. I started a branch here if you have an idea of what it should look like, and want to pick it up: https://github.com/philip-peterson/rust-rdom/compare/enum-nodes?expand=1

That said, I will probably still continue with the macro rewrite since I have an idea of how it will look.

**Comment by philip-peterson** [comment]
FWIW, I do keep coming back to this. I think it would be really nice to have (nicer than the macro approach actually), but the maintenance downside is that we'll have to rebuild the macros for the `nice` module, I think. I'll keep working on this spike, let me know if you'd like to join in.
